# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-json
      - id: pretty-format-json
        args: ['--autofix', '--no-sort-keys']
      - id: mixed-line-ending
        args: ['--fix=lf']

  # Secret detection
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package-lock\.json|pnpm-lock\.yaml|\.secrets\.baseline

  # Additional secret scanning with gitleaks
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.1
    hooks:
      - id: gitleaks

  # TypeScript/JavaScript specific
  - repo: local
    hooks:
      - id: eslint
        name: ESLint
        entry: pnpm run lint
        language: system
        files: \.(js|jsx|ts|tsx)$
        pass_filenames: false

      - id: typecheck
        name: TypeScript Check
        entry: pnpm run typecheck
        language: system
        files: \.tsx?$
        pass_filenames: false

  # Prettier formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx, css, markdown, json]
        additional_dependencies:
          - prettier@3.2.5
          - prettier-plugin-tailwindcss@0.5.11

  # Security checks for dependencies
  - repo: local
    hooks:
      - id: audit-dependencies
        name: Audit Dependencies
        entry: pnpm audit --audit-level=high
        language: system
        pass_filenames: false
        stages: [push]

# Configuration for detect-secrets
default_language_version:
  python: python3.11