global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9464']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '.*'
        target_label: __name__
        replacement: 'otel_${1}'

  # Scrape OpenTelemetry Collector internal metrics
  - job_name: 'otel-collector-internal'
    static_configs:
      - targets: ['otel-collector:8888']

  # Scrape Node.js application metrics (if exposed)
  - job_name: 'nextjs-app'
    static_configs:
      - targets: ['host.docker.internal:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s