apiVersion: v1
kind: Secret
metadata:
  name: ${DEPLOYMENT_NAME}-secrets
  namespace: ${K8S_NAMESPACE}
  labels:
    app: ${DEPLOYMENT_NAME}
type: Opaque
stringData:
  # Sensitive environment variables
  ANTHROPIC_API_KEY: "${ANTHROPIC_API_KEY}"
  SESSION_SECRET: "${SESSION_SECRET}"
  DATABASE_URL: "${DATABASE_URL}"
  REDIS_URL: "${REDIS_URL}"
  OTEL_EXPORTER_OTLP_HEADERS: "${OTEL_EXPORTER_OTLP_HEADERS}"